services:
  caddy:
    image: caddy:2.8-alpine
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"
      - "caddy_config:/config"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - infrastructure

volumes:
  caddy_data:
  caddy_config:

networks:
  infrastructure:
    external: true
