apiVersion: v1
kind: Secret
metadata:
  name: hasura-secret
type: Opaque
stringData:
  db-metadata-url: postgres://postgres:$POSTGRES_PASSWORD@postgres:5432/hasura
  db-buynow-url: postgres://postgres:$POSTGRES_PASSWORD@postgres:5432/buynow
  admin-secret: $HASURA_ADMIN_SECRET
