apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-script
data:
  init.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE buynow;
        CREATE DATABASE hasura;
    EOSQL
