apiVersion: batch/v1
kind: Job
metadata:
  name: hasura-migration
spec:
  template:
    spec:
      imagePullSecrets:
        - name: github-packages
      initContainers:
        - name: wait-for-hasura
          image: curlimages/curl:8.7.1
          command:
            - sh
            - -c
            - |
              until curl --fail http://hasura:8080/healthz; do
                echo "Waiting for Hasura to be ready..."
                sleep 2
              done

      containers:
        - name: hasura-migration
          image: ${HASURA_MIGRATION_IMAGE_NAME}
          env:
            - name: HASURA_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: hasura-secret
                  key: admin-secret
      restartPolicy: OnFailure
