apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-deployment
  labels:
    app: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      initContainers:
        - name: check-postgres
          image: "postgres:16.2"
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -p 5432; do
                echo waiting for database
                sleep 2
              done
      containers:
        - name: hasura
          image: "hasura/graphql-engine:v2.38.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hasura-secret
                  key: db-metadata-url
            - name: BUYNOW_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hasura-secret
                  key: db-buynow-url
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: hasura-secret
                  key: admin-secret
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            - name: HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS
              value: "false"
            - name: HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS
              value: "true"
            - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
              value: public

          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 250m
              memory: 500Mi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
