apiVersion: batch/v1
kind: Job
metadata:
  name: hasura-migration
spec:
  template:
    spec:
      imagePullSecrets:
        - name: github-packages
      initContainers:
        - name: check-postgres
          image: postgres:16.2
          command:
            - sh
            - -c
            - |
              until curl --fail http://hasura:8080/healthz; do
                echo "Waiting for Hasura to be ready..."
                sleep 2
              done

      containers:
        - name: hasura-migration
          image: ${HASURA_MIGRATION_IMAGE_NAME}
          env:
            - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hasura-secret
                  key: db-metadata-url
      restartPolicy: OnFailure
