services:
  db-backup:
    image: buynow/db-backup
    build:
      context: ./db-backup
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - S3_BUCKET=$S3_BACKUP_BUCKET
      - AWS_ENDPOINT_URL=https://s3.ir-thr-at1.arvanstorage.ir

networks:
  blue-network:
    external: true
