apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      imagePullSecrets:
        - name: github-packages
      initContainers:
        - name: check-postgres
          image: postgres:16.2
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -p 5432; do
                echo waiting for database
                sleep 2
              done

      containers:
        - name: db-migration
          image: ${DB_MIGRATION_IMAGE_NAME}
          args:
            - "migrate"
            - "apply"
            - "--url"
            - "postgres://postgres:$(POSTGRES_PASSWORD)@postgres:5432/buynow?sslmode=disable"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
      restartPolicy: OnFailure
