name: deploy
on: push
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - name: test secrets and env
        run: |
          echo "kube version env: ${{ env.ARVAN_KUBE_VERSION }}"
          echo "kube version secrets: ${{ secrets.ARVAN_KUBE_VERSION }}"
