name: deploy
on: push
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy to cluster
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ secrets.ARVAN_KUBE_VERSION }}

      - name: Apply kubeconfig
        run: echo "${{ secrets.ARVAN_KUBE_CONFIG }}" | kubectl apply -f -

      - name: Kubectl version
        run: kubectl version
